### ISSUE TITLE
Different character rendering between dokuwiki and exported odt document

### ISSUE THREAD

**Issue by GillesP227** [lpaulsen93/dokuwiki-plugin-odt#257]
Some characters have a specific syntax in dokuwiki that is not interpreted by the odt plugin :

- dokuwiki displays << as the character «, not the odt plugin, which keeps the original <<
- same for >> , displayed as » in dokuwiki, and --- as —, both kept as original and not translated by the odt plugin

Maybe other translations missing ...

Hope this helps...

**Comment by lpaulsen93** [comment]
This should be fixed now.
