### ISSUE TITLE
Table with merged cells does not export to ODT (unreadable content found)

### ISSUE THREAD

**Issue by Sayuuk** [lpaulsen93/dokuwiki-plugin-odt#258]
If you merge cells in dokuwiki (no plugins used), it will create unreadable content for Word when exporting - letting Word try to fix it scrambles the table layout.

No problem:
`| a | b |

| c | d |`

Bug:
`| a ||

| b | c |`

**Comment by lpaulsen93** [comment]
I do not have MS Word. Does it work if you open the exported document in LibreOffice?

**Comment by Sayuuk** [comment]
It works in LibreOffice - "sadly".

"Workaround":
If you open then save the exported ODT in LibreOffice (v7 portable), you can open it fine in Word. Word will not open it straight out of the exporter.

I know this means it may be a Word bug, but is there a chance to implement a change to make this work with Word with the information above?

I'd be willing to be the guinea pig, since you don't own Word.

**Comment by lpaulsen93** [comment]
> If you open then save the exported ODT in LibreOffice (v7 portable), you can open it fine in Word.

Ok, that means I can try to check the format LibreOffice is generating for merged cells and hopefully I can spot the difference. I will come back to you once there is a version for testing.

**Comment by lpaulsen93** [comment]
I did a change in `https://github.com/lpaulsen93/dokuwiki-plugin-odt/archive/word-compat.zip`. Please install from that URL manually and re-test and report the results (a first test - might still fail).

**Comment by Sayuuk** [comment]
Sorry, does not make any difference.

**Comment by lpaulsen93** [comment]
Please test again (un-install and then re-install manually from `https://github.com/lpaulsen93/dokuwiki-plugin-odt/archive/word-compat.zip`).

**Comment by Sayuuk** [comment]
Works!!1

Thank you so much for the quick work.

Guten Rutsch!

**Comment by Sayuuk** [comment]
Sorry, had to reopen this.

After using the new version on an actual document (not a test file), I've noticed that somewhere between the last release and the current one something in general about table handling must have happened.

In screenshot 1 you can see that the column width is affected (the top "table" is created with the column plugin in DW and actually looks normal, the bottom one is just a standard table in DW.

In screenshots 2/3 you can see that all tables are affected by this, though most not as disturbingly as in example 1.

I'm posting this here as it is the result of a "prerelease" and I'm not sure if it is directly related to the current fix...

Cheers!
![one](https://user-images.githubusercontent.com/13928660/103374572-36571480-4ad8-11eb-9a28-ff29e259bff8.PNG)
![three](https://user-images.githubusercontent.com/13928660/103374573-3820d800-4ad8-11eb-859b-710d1aa3d41d.PNG)
![two](https://user-images.githubusercontent.com/13928660/103374574-38b96e80-4ad8-11eb-9f67-f00d09315091.PNG)

**Comment by Sayuuk** [comment]
Oh, and before I forget, this is apparently a Word thing again, as both versions look identical in LibreOffice - though they both look... bad IMO... ;-)
![four](https://user-images.githubusercontent.com/13928660/103374742-a5346d80-4ad8-11eb-9685-cd2a86cb904c.PNG)

**Comment by Sayuuk** [comment]
And some more details:
With the old version, enabling "Editing" mode in Word does not change the table layout.
With the new version, doing so changes the layout (I've attached another screenshot because it is harder to describe:

Left: new version when opening, Right: new version after clicking "enable Editing"
![edit](https://user-images.githubusercontent.com/13928660/103415764-eafa4000-4b83-11eb-85c6-f40b65bdb0f2.PNG)

**Comment by lpaulsen93** [comment]
I think that this is all because my last change inserts a column style on each column without a style.

Before my change, a normal DokuWiki table resulted in an ODT table without any column styles assigned. Now, a column style is assigned and this (right now) leads also to a width being assigned to the table column.

In the next step I will try to assign an empty style to the column (making MS Word accept the format) but without any width set (to hopefully get better layout behavior). I hope MS Word will still accept that format.

But that won't happen today :wink: I will notify you when the change is ready for testing. Thanks for all the testing so far :+1:

**Comment by lpaulsen93** [comment]
Ok, another try, please test again (un-install and then re-install manually from https://github.com/lpaulsen93/dokuwiki-plugin-odt/archive/word-compat.zip).

As mentioned this time column styles are empty without having a width set. Let's see if this is still accepted by MS Word and what the layout looks like.

**Comment by Sayuuk** [comment]
Alright, so:

a) exporting merged cells
does not open in Word

b) exporting "most" of my pages (cannot find the issue yet)
does not open in Word

c) test page with just a 2x2 table in it
opens normally

b²)opening then saving in LO will make it open in Word, but the style (i.e. width etc) is still "messed up", even when not in Editing mode (i.e. oh no, it's from the internet read-only mode)

Thanks for investing so much time in this... ;-)

**Comment by lpaulsen93** [comment]
> a) exporting merged cells
does not open in Word

That is bad because that means the ODT plugin needs to set/assign an width otherwise MS Word will not accept the document. But that would mean (as seen in the working attempt) that the plugin would assign the same width to all columns of a table (in a table with 2 columns each column would have a 50% width, in a table with 2 columns each column would have a 33% width...). But that would be the only solution right now to make it work in MS Word.

**There might be a workaround:**
Did you try to use plugins for your tables? The [exttab3 plugin](https://www.dokuwiki.org/plugin:exttab3) allows to set styles for tables and supports ODT export. E.g. if the example bellow is exported to ODT then the width ratio of the exported table will match the ratio of the HTML version:

```
{|
|+//Extended Table Example//
! style="width: 10cm;" |
A1 Header
! style="width: 5cm;" |
B1 Header
! style="width: 5cm;" |
C1 Header
|-
|
{{ wiki:dokuwiki-128.png?50&nolink}}
Lorem ipsum dolor sit amet, 
consetetur sadipscing elitr, 
sed diam nonumy eirmod tempor invidunt
ut labore et dolore magna aliquyam erat, 
sed diam voluptua.
|
Lorem ipsum dolor sit amet, 
consetetur sadipscing elitr, 
sed diam nonumy eirmod tempor invidunt
ut labore et dolore magna aliquyam erat, 
sed diam voluptua.
|
Lorem ipsum dolor sit amet, 
consetetur sadipscing elitr, 
sed diam nonumy eirmod tempor invidunt
ut labore et dolore magna aliquyam erat, 
sed diam voluptua.
|-
|
Lorem ipsum dolor sit amet, 
consetetur sadipscing elitr, 
sed diam nonumy eirmod tempor invidunt
ut labore et dolore magna aliquyam erat, 
sed diam voluptua.
|
Lorem ipsum dolor sit amet, 
consetetur sadipscing elitr, 
sed diam nonumy eirmod tempor invidunt
ut labore et dolore magna aliquyam erat, 
sed diam voluptua.
|
Lorem ipsum dolor sit amet, 
consetetur sadipscing elitr, 
sed diam nonumy eirmod tempor invidunt
ut labore et dolore magna aliquyam erat, 
sed diam voluptua.
|}
```

**Comment by Sayuuk** [comment]
Hmm, I've looked at the plugin, but that would mean I cannot use the WYSIWYG editors to edit those tables, which for my use case is... not great...

I acknowledge that this is some sort of Word ODT interpretation issue.

FYI though, apart from the merged cells, for me as a Word user the last official release is a lot more usable than the dev one. But that might mean I'll just have to stay on that version and hope it doesn't actually break.

Thanks for all the work though!

**Comment by lpaulsen93** [comment]
> I acknowledge that this is some sort of Word ODT interpretation issue.

Well, true on the one hand. On the other hand the ODT plugin is not capable of calculation a cell's width. If it could it could apply different cell widths than just the same width across all columns. But honestly I dońt have the time and the will to built-in such a big change.

> FYI though, apart from the merged cells, for me as a Word user the last official release is a lot more usable than the dev one.

Thanks for the info. As there is no good solution I will NOT merge the changes I did for your testing to the official release.

> Thanks for all the work though!

Thank you too, for all the testing :+1: At least we know now what MS Word would expect.
