### ISSUE TITLE
Fractional page margins

### ISSUE THREAD

**Issue by fts-tmassey** [lpaulsen93/dokuwiki-plugin-odt#259]
Hello!

For those of us in backward measurement countries, a common margin is 2.54cm (also known as one inch).  Fractional margins are allowed in certain contexts (like TOC spacing), but are *not* allowed in page margins.

Could we please have fractional measurements on page margins, too?  Thank you very much!

**Comment by lpaulsen93** [comment]
Hi.

How did you try to set page margins? I am asking because it seems to work fine for me. E.g. if I use the syntax `{{odt>page:A3,landscape,2.54,2.54,2.54,2.54}}` the exported page has A3 landscape format with all margins set to 2.54 cm.

**Comment by fts-tmassey** [comment]
In the Configuration Manager.  If you use a decimal, it won’t let you save the changes.

**Comment by lpaulsen93** [comment]
> In the Configuration Manager. If you use a decimal, it won’t let you save the changes.

Ahh..ok. Can reproduce that, thanks.

**Comment by fts-tmassey** [comment]
Sometimes programmers are too close and too capable.  For us really basic users, we can only stick to the really basic options....  :)

**Comment by lpaulsen93** [comment]
This should be fixed now.
