### ISSUE TITLE
ODT Export fails when using wrap plugin in ordered/unorderd lists

### ISSUE THREAD

**Issue by bscholle** [lpaulsen93/dokuwiki-plugin-odt#268]
Hello,

if I use lists on my wiki page and add notes from the wrap plugin there, the ODT export fails. Apache responds with a 500 error.

DokuWiki: Release 2020-07-29 "Hogfather"
ODT-Plugin: Latest updated (2019-07-27)
PHP 7.4
Apache 2.4

Regards
Burghardt

**Comment by spricer** [comment]
This is probably duplicate of #254

**Comment by bscholle** [comment]
You are right, I close this issue.
Thanks.
