### ISSUE TITLE
 Invalid argument supplied for foreach() in [...] lib/plugins/odt/ODT/css/cssimportnew.php on line 1263

### ISSUE THREAD

**Issue by fjf2002** [lpaulsen93/dokuwiki-plugin-odt#288]
Hello,

I'm getting the following errors in apache's error.log.
I'm using PHP 7.2 and the latest dokuwiki.

>  Invalid argument supplied for foreach() in [...] lib/plugins/odt/ODT/css/cssimportnew.php on line 1263

**Comment by fjf2002** [comment]
Investigating the problem:

```php
$properties = $parent->getProperties();`
```
`$parent->getProperties()` seems to return NULL.
What about replacing the line by

```php
$properties = $parent->getProperties() ?? [];`
```

**Comment by Stikus** [comment]
Same problem here:
```
[root@wiki php-fpm]# grep -c 'Invalid argument supplied for foreach()' www-error.log
16480
[root@wiki php-fpm]# wc -l www-error.log
16565 www-error.log
```

**Comment by Stikus** [comment]
@Klap-in Hello, can you release some latest fixes or this plugin is looking for maintainer?

**Comment by Stikus** [comment]
Unfortunately these fixes happened at the beginning of the March, but release happened at the end of February so they are not included.

**Comment by Klap-in** [comment]
Sorry for the unhandy formulation, I mean I released a new version. Please see https://github.com/lpaulsen93/dokuwiki-plugin-odt/releases

**Comment by Stikus** [comment]
I should first check for new release, sorry. Thanks for it!

**Comment by Klap-in** [comment]
Thanks for the feedback.
